### ISSUE TITLE
Acceptable power range for setPerAntennaPower()

### ISSUE THREAD

**Issue by jtrenton** [NordicID/nur_nurapi_android#3]
Greetings. There's nothing in the Alien developer guide or the javadocs about an acceptable range of power. I assume the lowest power setting is 0. What's the highest? I am writing an application where a user can adjust power if they want.

**Comment by AriPoy** [comment]
TxLevel is actually transmission level attenuation value 0-19. 
0 is highest txlevel and 19 lowest and yes, I agree that information is difficult to find from our documentation. Sorry about that.

**Comment by jtrenton** [comment]
Yeah, I figured it out. Just kept trying values until it stopped throwing exceptions. 

Well... At least it's documented here now!
