### ISSUE TITLE
Not working on Android 12

### ISSUE THREAD

**Issue by cvalcke** [NordicID/nur_nurapi_android#5]
sdk seems to be uncompatible with Android 12. 
PendingIntent.getBroadcast method has changed and the last parameter is mandatory so the com.nordicid.nurapi.NurApiUsbAutoConnect#NurApiUsbAutoConnect method  crashes.

The permissions have changed in Android 12 to so the com.nordicid.nurapi.NurApiUsbAutoConnect#connect method not working too.

Tested on Samsung Galaxy Tab A7

**Comment by hehannul** [comment]
There is already all four parameters used for PendingIntent.getBroadcast  method. Last parameter seems not to be mandatory according to spec and spec says that flag value can be either 0 or combination of flags. Currently value 0 is used.

Or did you mean some other parameter than flag? 

Could you please test with latest release 2.0.31 that is issue still occurs?

Thanks!

**Comment by hehannul** [comment]
What kind of environment you have? Do you have own app whcvi uses NurApiAndroid.aar?

I tested with my environment and didn't get any errors. Maybe I have not noticed something?

I used OnePlus Nord CE 3 Lite 5G with Android 13 for testing.

I used Noirdic ID Android Sample (nur_sample_android repo) which contains NurApiAndroid library.
I tested with NurApiAndroid version 2.0.20 and latest 2.0.31 versions and both seems to work.

I enabled OTG Connection in phone settings and tested with Nordic RFID Demo (from Google Play). That app contains NurApiAndroid v.2.0.20 (based on about) and USB autoconenction seems to work. Connecting reader to USB opens RFID demo. Attach and detach reader from phone can be seen in app statusbar.

Is this issue still valid?

**Comment by hehannul** [comment]
Tested with OnePlus Nord CE 3 Lite 5G (Android 13) and works.
Used Stix reader for testing.

What reader is used,?

**Comment by hehannul** [comment]
I tested this wrongly and it works in my environment, because test app that used this library was not targeted to Android 12 or 13. I didn't noticed that earlier. 

Now I got same error and after fixing it, USB connection to reader is working properly.
Tested on Android 13 device with Stix.

NurApiAndorid.aar version 2.0.50 fix this issue.
Issue can be closed.

**Comment by hehannul** [comment]
Bug fixed, by using right parameters. Tested with Android 13 with Stix reader without errors.
Version 2.0.50 fix the bug
